---
- name: Install and assess operand
  ansible.builtin.include_tasks: install.yml
  when: role_mode == 'install' or role_mode == ''
  tags:
    - install

- name: Cleanup operator
  ansible.builtin.include_tasks: cleanup.yml
  when: role_mode == 'cleanup' or role_mode == ''
  tags:
    - cleanup
