apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: apimanager-sample
spec:
  wildcardDomain: 3scale.${CLUSTER_BASE_URL}
  system:
    fileStorage:
      simpleStorageService:
        configurationSecretRef:
          name: aws-auth
