apiVersion: apps.3scale.net/v1alpha1
kind: APIcast
metadata:
  name: example-apicast-staging
spec:
  deploymentEnvironment: staging
  configurationLoadMode: lazy
  adminPortalCredentialsRef:
    name: 3scaleportal
